import '../styles/index.scss'
import './includes/_lazyloading'
import './includes/_plyr-player'
import './includes/_youtube-players-initialization'
import './includes/_floating-action-button'
import './includes/_diver-onscroll-animation'